export const PAKISTAN_CITIES = [
  "Karachi",
  "Lahore",
  "Islamabad",
  "Rawalpindi",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad",
  "Sargodha",
  "Bahawalpur",
  "Sukkur",
  "Larkana",
  "Sheikhupura",
  "Mardan",
  "Gujrat",
  "Kasur",
  "Rahim Yar Khan",
  "Sahiwal",
  "Okara",
  "Wah Cantonment",
  "Dera Ghazi Khan",
  "Mirpur",
  "Nawabshah",
  "Mingora",
  "Chiniot",
  "Kamoke",
  "Hafizabad",
  "Kohat",
  "Jacobabad",
  "Shikarpur",
  "Muzaffargarh",
  "Khanpur",
  "Gojra",
  "Abbottabad",
  "Murree",
  "Gwadar",
  "Taxila",
  "Mansehra",
  "Haripur",
  "Nowshera",
  "Charsadda",
  "Swabi",
  "Bannu",
  "Dera Ismail Khan",
  "Gilgit",
  "Skardu",
  "Hunza",
].sort();

/** @deprecated Use PAKISTAN_CITIES */
export const NETHERLANDS_CITIES = PAKISTAN_CITIES;
