export const API_ROUTES = {
    AUTH_REGISTER: `/auth/register`,
    AUTH_LOGIN: `/auth/login`,
    AUTH_LOGOUT: `/auth/logout`,
    AUTH_FORGOT_PASSWORD: `/auth/forgot-password`,
    AUTH_RESET_PASSWORD: `/auth/reset-password`,
    AUTH_VERIFY_EMAIL: `/auth/verify-email`,
    AUTH_RESEND_VERIFICATION: `/auth/resend-verification`,
    AUTH_REFRESH: `/auth/refresh`,
    AUTH_ME: `/auth/me`,
    AUTH_LOGOUT_ALL: `/auth/logout-all`,
    PUBLIC_SETTINGS: `/settings/public`,
    NEWSLETTER_SUBSCRIBE: `/newsletter`,
    CONTACT: `/contact`,
    QUOTE: `/vehicle-pricing/quote`,
    HOURLY_DURATIONS: `/hourly-pricing/durations`,
    VEHICLE_CATEGORIES: `/vehicle-categories`,
    DRIVERS_APPLY: `/drivers/apply`,
    BOOKINGS: `/bookings`,
    PAYMENTS: `/payments`,
    CHECKOUT_SESSION: `/bookings`,
    UPLOAD: `/upload`,
    // User dashboard
    USER_DASHBOARD_OVERVIEW: `/user/overview`,
    USER_DASHBOARD_BOOKINGS: `/user/bookings`,
    USER_DASHBOARD_PAYMENTS: `/user/payments`,
} as const;
export default API_ROUTES;